### PR TITLE
Add screenshots to readme

### PR DESCRIPTION
**Pull request by migerh**
See #1.

### CODE REVIEW

**Comment by fitzgen** [comment]
@migerh thank you! This project is using `cargo readme` to turn the crate level docs into a README.md, so the proper way to make this change is to add the screenshot links to the crate level docs in `src/lib.rs` and then re-run `cargo readme`.

If you don't already have it installed, you can do `cargo install cargo-readme`.

This is why the tests are failing right now, they assert that running `cargo readme` doesn't change the README (meaning that its already been run and the changes committed).

Thanks!

**Comment by fitzgen** [comment]
Also, sorry I didn't make this clear earlier, I had forgotten that this project used `cargo readme`.

**Comment by migerh** [comment]
No worries! Who'd have thought adding screenshots could be so complicated ;) And I learned that cargo-readme exists, that's something.

Travis still fails but I guess this is due to `wasm_custom_section` being stable now.

**Comment by fitzgen** [comment]
Thanks! Will fix the wasm custom section stuff later today after a new wasm-bindgen release.

**Pull request merged**
